# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20160314_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
