# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_auto_20160316_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
