# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0013_auto_20160318_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='roll_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
