# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20160318_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(default='sathyam', max_length=120),
        ),
    ]
