# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_auto_20160318_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
    ]
