# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_auto_20160417_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='auth',
            field=models.BigIntegerField(),
        ),
    ]
