# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_auto_20160417_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='auth',
            field=models.BooleanField(default=True),
        ),
    ]
