# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_auto_20160417_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='uid',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='signup',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
