# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0025_auto_20160418_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='uid',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
