# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0026_auto_20160418_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='maxno',
            field=models.PositiveIntegerField(blank=True, default='0'),
        ),
    ]
