# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to='tp/'),
        ),
    ]
