# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0003_auto_20160320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
