# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0004_auto_20160320_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
