# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0005_filedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
