# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0006_auto_20160321_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='title',
        ),
    ]
