# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0007_remove_filedata_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
