# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import flupld.models


class Migration(migrations.Migration):

    dependencies = [
        ('flupld', '0008_folderdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to=flupld.models.get_path),
        ),
    ]
